name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: 4.5.0
api-version: 1.17
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]
